nxus-4 work in progress
seabourne/nxus-dataset pull request #3
Opened 2016-10-17 16:41 UTC by ScottMaxson

For early review - files have been pulled from "modules" of app-boilerplate so this isn't yet packaged as stand-alone nxus module yet.

2016-10-17 18:08 UTC, alexjreich requested changes
General comments:
- Need to follow coding conventions (https://github.com/nxus/core/issues/51)

2016-10-17 18:08 UTC, alexjreich commented on controllers/DataPresentationAdmin.js
> +    if (presentId) {
Hrm...this makes me want a createOrUpdate method. @loppear what do you think about adding this to our base Storage Model class?

2016-10-17 18:08 UTC, alexjreich commented on controllers/DataPresentationAdmin.js
> +      return [this.models['datasets-dataset'].find(), editContext]
Rather than hard-coding, would recommend you keep this as an instance variable similar to modelIdentity (may not ever be over-ridden, but at least provides the opportunity for an app using this module to provide its own class definition.

2016-10-17 18:08 UTC, alexjreich commented on controllers/DataSetAdmin.js
> +      if (typeof(val) == 'string') {
For sake of clarity, you might think about moving these `if` checks in to a util class/file.  Also, there are some NPM modules that do the float/decimal checking, maybe worth using those instead of coding your own test (likely to have better testing, etc)

2016-10-17 18:08 UTC, mjreich commented on controllers/DataSetAdmin.js
> +    this.log.debug("save DataSet id: ", dataSetId)
A note on style here: generally, I think the best practice is to do your checking for exceptions/validation at the top, then have the body of the method be the normal path.  So here, I might rewrite as:

```javascript
save(req, res) {
  return Promise.resolve().then(() => {
    if(!dataSetId && !req.body.name) throw new Error("Name is required")
    if(!dataSetId && req.body.name) return this.model.create({name: req.body.name, source: req.body.source, description: req.body.description})
    ....
  }).then((record) =>{
    this.log.debug("dataset created", record.id)
    return res.redirect(this.routePrefix)
  }).catch((e) => {
    req.flash('error', e)
    return res.redirect(this.routePrefix + '/create')
  })
})
```

2016-10-17 18:08 UTC, mjreich commented on controllers/DataSetAdmin.js
> +      .then((dataset) => {
For readability, you might think about moving this into a private method

2016-10-17 18:08 UTC, mjreich commented on controllers/DataSetAdmin.js
> +        _.each( req.body, (value,key) => {
What's the purpose here? Supporting foreign key relationships?

2016-10-17 18:14 UTC, loppear commented on controllers/DataPresentationAdmin.js
> +    if (presentId) {
BaseModel.createOrUpdate exists today for this.

2016-10-17 18:19 UTC, loppear commented on controllers/DataPresentationAdmin.js
> +    if (presentId) {
Er, though that assumes you have some key field to search by besides ID - it probably reasonably should accept a non-object criteria object and act as this does (just doing a create without the ID) if it's null.

2016-10-17 18:33 UTC, loppear commented on controllers/DataSetAdmin.js
> +    //TODO - adjust when the data-manager is ready for use
A couple TODO comments like this that are outdated, right?

2016-10-17 18:33 UTC, loppear commented on controllers/DataSetAdmin.js
> +      this.log.debug( "find returned matched datarows:  ", datarows)
Question about some of these debug outputs, my feeling is that general debug lines should not dump full objects in most cases (not just be an equivalent of all the places you needed a console.log) - should still be reasonable to run with debug=true and use the log output. So are all these debugs generally useful?

2016-10-17 18:33 UTC, loppear commented on controllers/DataSetAdmin.js
> +      req.flash('error', "Error processing rows")
can we include some part of the exception in this user message?

2016-10-17 18:33 UTC, loppear commented on controllers/DataSetAdmin.js
> +        if (val.endsWith('%')) {
Would ideally like to consolidate into a shared or existing library for this type validation and parsing

2016-10-17 18:33 UTC, loppear commented on controllers/DataSetAdmin.js
> +            let pComponents = key.split('_')
These name conventions (field_whatever_? and isSomething), are they coordinated by something on the client side I'm not seeing here or are they just specific to WPSP's original data?

2016-10-17 18:33 UTC, loppear commented on index.js
> +import {fieldConstants} from './fieldConstants'
presumably this doesn't work and exports a null below.

2016-10-17 18:33 UTC, loppear commented on models/DataPresentation.js
> +DataPresentation.extractUsingFieldIds = (presentation, datasets, datarows) => {
Is there a reason this is a static class method that takes an instance as the first argument, rather than being an instance method and using `this`?

2016-10-19 18:22 UTC, ScottMaxson commented on controllers/DataPresentationAdmin.js
> +    if (presentId) {
seems like this works (in a NxusModule), and is relatively safe:

```
let myId = req.params.id || null
this.model.createOrUpdate({id: myId}, { ... stuff from request here ...})
```

2016-10-19 20:53 UTC, ScottMaxson commented on controllers/DataSetAdmin.js
> +      if (typeof(val) == 'string') {
After some searching, no NPM module jumps out that does more than simple string->number conversion. Did you have a suggestion? Splitting this off into it's own class does make a lot of sense, so working on that.

2016-10-25 14:25 UTC, alexjreich reviewed
Looks good overall!  A couple of small suggestions.

2016-10-25 14:25 UTC, mjreich commented on src/controllers/DataSetAdmin.js
> +      this.log.debug( "nxus-dataset error removing data rows from dataset " + dataSetId, e);
Probably want this to use `log.error` so it'll show up on a production environment.

2016-10-25 14:25 UTC, mjreich commented on src/index.js
> +import {MVCModule} from 'nxus-web'
Did the Usage documentation move somewhere else?

2016-10-25 17:08 UTC, ScottMaxson commented on src/index.js
> +import {MVCModule} from 'nxus-web'
It's in the README. Would it be better someplace else?

2016-11-17 14:54 UTC, mjreich commented
@ScottMaxson overall looks good.  I'd go ahead and merge the branch, and do more granular PRs going forward (makes it easier to review specific changes 😄 )

2016-11-17 14:55 UTC, alexjreich approved these changes

2016-11-18 17:22 UTC, merged